version: "2"
services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo